// Code generated by ent, DO NOT EDIT.

package languagedetection

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the languagedetection type in the database.
	Label = "language_detection"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldQuery holds the string denoting the query field in the database.
	FieldQuery = "query"
	// FieldDetectedLanguages holds the string denoting the detected_languages field in the database.
	FieldDetectedLanguages = "detected_languages"
	// FieldDuration holds the string denoting the duration field in the database.
	FieldDuration = "duration"
	// FieldModelName holds the string denoting the model_name field in the database.
	FieldModelName = "model_name"
	// FieldInputToken holds the string denoting the input_token field in the database.
	FieldInputToken = "input_token"
	// FieldOutputToken holds the string denoting the output_token field in the database.
	FieldOutputToken = "output_token"
	// FieldCachedToken holds the string denoting the cached_token field in the database.
	FieldCachedToken = "cached_token"
	// FieldOwnerID holds the string denoting the owner_id field in the database.
	FieldOwnerID = "owner_id"
	// FieldCost holds the string denoting the cost field in the database.
	FieldCost = "cost"
	// Table holds the table name of the languagedetection in the database.
	Table = "language_detections"
)

// Columns holds all SQL columns for languagedetection fields.
var Columns = []string{
	FieldID,
	FieldQuery,
	FieldDetectedLanguages,
	FieldDuration,
	FieldModelName,
	FieldInputToken,
	FieldOutputToken,
	FieldCachedToken,
	FieldOwnerID,
	FieldCost,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ModelNameValidator is a validator for the "model_name" field. It is called by the builders before save.
	ModelNameValidator func(string) error
)

// OrderOption defines the ordering options for the LanguageDetection queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByQuery orders the results by the query field.
func ByQuery(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuery, opts...).ToFunc()
}

// ByDuration orders the results by the duration field.
func ByDuration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDuration, opts...).ToFunc()
}

// ByModelName orders the results by the model_name field.
func ByModelName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelName, opts...).ToFunc()
}

// ByInputToken orders the results by the input_token field.
func ByInputToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputToken, opts...).ToFunc()
}

// ByOutputToken orders the results by the output_token field.
func ByOutputToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputToken, opts...).ToFunc()
}

// ByCachedToken orders the results by the cached_token field.
func ByCachedToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCachedToken, opts...).ToFunc()
}

// ByOwnerID orders the results by the owner_id field.
func ByOwnerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerID, opts...).ToFunc()
}

// ByCost orders the results by the cost field.
func ByCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCost, opts...).ToFunc()
}
