// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"ent/ent/languagedetection"
	"ent/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LanguageDetectionDelete is the builder for deleting a LanguageDetection entity.
type LanguageDetectionDelete struct {
	config
	hooks    []Hook
	mutation *LanguageDetectionMutation
}

// Where appends a list predicates to the LanguageDetectionDelete builder.
func (_d *LanguageDetectionDelete) Where(ps ...predicate.LanguageDetection) *LanguageDetectionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *LanguageDetectionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LanguageDetectionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *LanguageDetectionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(languagedetection.Table, sqlgraph.NewFieldSpec(languagedetection.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// LanguageDetectionDeleteOne is the builder for deleting a single LanguageDetection entity.
type LanguageDetectionDeleteOne struct {
	_d *LanguageDetectionDelete
}

// Where appends a list predicates to the LanguageDetectionDelete builder.
func (_d *LanguageDetectionDeleteOne) Where(ps ...predicate.LanguageDetection) *LanguageDetectionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *LanguageDetectionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{languagedetection.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LanguageDetectionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
