// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"ent/ent/languagedetection"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LanguageDetectionCreate is the builder for creating a LanguageDetection entity.
type LanguageDetectionCreate struct {
	config
	mutation *LanguageDetectionMutation
	hooks    []Hook
}

// SetQuery sets the "query" field.
func (_c *LanguageDetectionCreate) SetQuery(v string) *LanguageDetectionCreate {
	_c.mutation.SetQuery(v)
	return _c
}

// SetDetectedLanguages sets the "detected_languages" field.
func (_c *LanguageDetectionCreate) SetDetectedLanguages(v map[string]interface{}) *LanguageDetectionCreate {
	_c.mutation.SetDetectedLanguages(v)
	return _c
}

// SetDuration sets the "duration" field.
func (_c *LanguageDetectionCreate) SetDuration(v int64) *LanguageDetectionCreate {
	_c.mutation.SetDuration(v)
	return _c
}

// SetModelName sets the "model_name" field.
func (_c *LanguageDetectionCreate) SetModelName(v string) *LanguageDetectionCreate {
	_c.mutation.SetModelName(v)
	return _c
}

// SetInputToken sets the "input_token" field.
func (_c *LanguageDetectionCreate) SetInputToken(v int) *LanguageDetectionCreate {
	_c.mutation.SetInputToken(v)
	return _c
}

// SetOutputToken sets the "output_token" field.
func (_c *LanguageDetectionCreate) SetOutputToken(v int) *LanguageDetectionCreate {
	_c.mutation.SetOutputToken(v)
	return _c
}

// SetCachedToken sets the "cached_token" field.
func (_c *LanguageDetectionCreate) SetCachedToken(v int) *LanguageDetectionCreate {
	_c.mutation.SetCachedToken(v)
	return _c
}

// SetOwnerID sets the "owner_id" field.
func (_c *LanguageDetectionCreate) SetOwnerID(v string) *LanguageDetectionCreate {
	_c.mutation.SetOwnerID(v)
	return _c
}

// SetCost sets the "cost" field.
func (_c *LanguageDetectionCreate) SetCost(v float64) *LanguageDetectionCreate {
	_c.mutation.SetCost(v)
	return _c
}

// Mutation returns the LanguageDetectionMutation object of the builder.
func (_c *LanguageDetectionCreate) Mutation() *LanguageDetectionMutation {
	return _c.mutation
}

// Save creates the LanguageDetection in the database.
func (_c *LanguageDetectionCreate) Save(ctx context.Context) (*LanguageDetection, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LanguageDetectionCreate) SaveX(ctx context.Context) *LanguageDetection {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LanguageDetectionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LanguageDetectionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LanguageDetectionCreate) check() error {
	if _, ok := _c.mutation.Query(); !ok {
		return &ValidationError{Name: "query", err: errors.New(`ent: missing required field "LanguageDetection.query"`)}
	}
	if _, ok := _c.mutation.DetectedLanguages(); !ok {
		return &ValidationError{Name: "detected_languages", err: errors.New(`ent: missing required field "LanguageDetection.detected_languages"`)}
	}
	if _, ok := _c.mutation.Duration(); !ok {
		return &ValidationError{Name: "duration", err: errors.New(`ent: missing required field "LanguageDetection.duration"`)}
	}
	if _, ok := _c.mutation.ModelName(); !ok {
		return &ValidationError{Name: "model_name", err: errors.New(`ent: missing required field "LanguageDetection.model_name"`)}
	}
	if v, ok := _c.mutation.ModelName(); ok {
		if err := languagedetection.ModelNameValidator(v); err != nil {
			return &ValidationError{Name: "model_name", err: fmt.Errorf(`ent: validator failed for field "LanguageDetection.model_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InputToken(); !ok {
		return &ValidationError{Name: "input_token", err: errors.New(`ent: missing required field "LanguageDetection.input_token"`)}
	}
	if _, ok := _c.mutation.OutputToken(); !ok {
		return &ValidationError{Name: "output_token", err: errors.New(`ent: missing required field "LanguageDetection.output_token"`)}
	}
	if _, ok := _c.mutation.CachedToken(); !ok {
		return &ValidationError{Name: "cached_token", err: errors.New(`ent: missing required field "LanguageDetection.cached_token"`)}
	}
	if _, ok := _c.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner_id", err: errors.New(`ent: missing required field "LanguageDetection.owner_id"`)}
	}
	if _, ok := _c.mutation.Cost(); !ok {
		return &ValidationError{Name: "cost", err: errors.New(`ent: missing required field "LanguageDetection.cost"`)}
	}
	return nil
}

func (_c *LanguageDetectionCreate) sqlSave(ctx context.Context) (*LanguageDetection, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LanguageDetectionCreate) createSpec() (*LanguageDetection, *sqlgraph.CreateSpec) {
	var (
		_node = &LanguageDetection{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(languagedetection.Table, sqlgraph.NewFieldSpec(languagedetection.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Query(); ok {
		_spec.SetField(languagedetection.FieldQuery, field.TypeString, value)
		_node.Query = value
	}
	if value, ok := _c.mutation.DetectedLanguages(); ok {
		_spec.SetField(languagedetection.FieldDetectedLanguages, field.TypeJSON, value)
		_node.DetectedLanguages = value
	}
	if value, ok := _c.mutation.Duration(); ok {
		_spec.SetField(languagedetection.FieldDuration, field.TypeInt64, value)
		_node.Duration = value
	}
	if value, ok := _c.mutation.ModelName(); ok {
		_spec.SetField(languagedetection.FieldModelName, field.TypeString, value)
		_node.ModelName = value
	}
	if value, ok := _c.mutation.InputToken(); ok {
		_spec.SetField(languagedetection.FieldInputToken, field.TypeInt, value)
		_node.InputToken = value
	}
	if value, ok := _c.mutation.OutputToken(); ok {
		_spec.SetField(languagedetection.FieldOutputToken, field.TypeInt, value)
		_node.OutputToken = value
	}
	if value, ok := _c.mutation.CachedToken(); ok {
		_spec.SetField(languagedetection.FieldCachedToken, field.TypeInt, value)
		_node.CachedToken = value
	}
	if value, ok := _c.mutation.OwnerID(); ok {
		_spec.SetField(languagedetection.FieldOwnerID, field.TypeString, value)
		_node.OwnerID = value
	}
	if value, ok := _c.mutation.Cost(); ok {
		_spec.SetField(languagedetection.FieldCost, field.TypeFloat64, value)
		_node.Cost = value
	}
	return _node, _spec
}

// LanguageDetectionCreateBulk is the builder for creating many LanguageDetection entities in bulk.
type LanguageDetectionCreateBulk struct {
	config
	err      error
	builders []*LanguageDetectionCreate
}

// Save creates the LanguageDetection entities in the database.
func (_c *LanguageDetectionCreateBulk) Save(ctx context.Context) ([]*LanguageDetection, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LanguageDetection, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LanguageDetectionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LanguageDetectionCreateBulk) SaveX(ctx context.Context) []*LanguageDetection {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LanguageDetectionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LanguageDetectionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
