// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ent/ent/languagedetection"
	"ent/ent/schema"
	"ent/ent/transcriptionstats"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	languagedetectionFields := schema.LanguageDetection{}.Fields()
	_ = languagedetectionFields
	// languagedetectionDescModelName is the schema descriptor for model_name field.
	languagedetectionDescModelName := languagedetectionFields[3].Descriptor()
	// languagedetection.ModelNameValidator is a validator for the "model_name" field. It is called by the builders before save.
	languagedetection.ModelNameValidator = languagedetectionDescModelName.Validators[0].(func(string) error)
	transcriptionstatsFields := schema.TranscriptionStats{}.Fields()
	_ = transcriptionstatsFields
	// transcriptionstatsDescModelName is the schema descriptor for model_name field.
	transcriptionstatsDescModelName := transcriptionstatsFields[3].Descriptor()
	// transcriptionstats.ModelNameValidator is a validator for the "model_name" field. It is called by the builders before save.
	transcriptionstats.ModelNameValidator = transcriptionstatsDescModelName.Validators[0].(func(string) error)
}
