// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"ent/ent/transcriptionstats"
	"ent/ent/translation"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TranslationCreate is the builder for creating a Translation entity.
type TranslationCreate struct {
	config
	mutation *TranslationMutation
	hooks    []Hook
}

// SetContent sets the "content" field.
func (_c *TranslationCreate) SetContent(v string) *TranslationCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetChoices sets the "choices" field.
func (_c *TranslationCreate) SetChoices(v []map[string]interface{}) *TranslationCreate {
	_c.mutation.SetChoices(v)
	return _c
}

// SetExternalID sets the "external_id" field.
func (_c *TranslationCreate) SetExternalID(v string) *TranslationCreate {
	_c.mutation.SetExternalID(v)
	return _c
}

// SetLanguagePair sets the "language_pair" field.
func (_c *TranslationCreate) SetLanguagePair(v string) *TranslationCreate {
	_c.mutation.SetLanguagePair(v)
	return _c
}

// SetOwnerID sets the "owner_id" field.
func (_c *TranslationCreate) SetOwnerID(v string) *TranslationCreate {
	_c.mutation.SetOwnerID(v)
	return _c
}

// AddTranscriptionStatIDs adds the "transcription_stats" edge to the TranscriptionStats entity by IDs.
func (_c *TranslationCreate) AddTranscriptionStatIDs(ids ...int) *TranslationCreate {
	_c.mutation.AddTranscriptionStatIDs(ids...)
	return _c
}

// AddTranscriptionStats adds the "transcription_stats" edges to the TranscriptionStats entity.
func (_c *TranslationCreate) AddTranscriptionStats(v ...*TranscriptionStats) *TranslationCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTranscriptionStatIDs(ids...)
}

// Mutation returns the TranslationMutation object of the builder.
func (_c *TranslationCreate) Mutation() *TranslationMutation {
	return _c.mutation
}

// Save creates the Translation in the database.
func (_c *TranslationCreate) Save(ctx context.Context) (*Translation, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TranslationCreate) SaveX(ctx context.Context) *Translation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TranslationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TranslationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TranslationCreate) check() error {
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Translation.content"`)}
	}
	if _, ok := _c.mutation.Choices(); !ok {
		return &ValidationError{Name: "choices", err: errors.New(`ent: missing required field "Translation.choices"`)}
	}
	if _, ok := _c.mutation.ExternalID(); !ok {
		return &ValidationError{Name: "external_id", err: errors.New(`ent: missing required field "Translation.external_id"`)}
	}
	if _, ok := _c.mutation.LanguagePair(); !ok {
		return &ValidationError{Name: "language_pair", err: errors.New(`ent: missing required field "Translation.language_pair"`)}
	}
	if _, ok := _c.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner_id", err: errors.New(`ent: missing required field "Translation.owner_id"`)}
	}
	return nil
}

func (_c *TranslationCreate) sqlSave(ctx context.Context) (*Translation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TranslationCreate) createSpec() (*Translation, *sqlgraph.CreateSpec) {
	var (
		_node = &Translation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(translation.Table, sqlgraph.NewFieldSpec(translation.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(translation.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Choices(); ok {
		_spec.SetField(translation.FieldChoices, field.TypeJSON, value)
		_node.Choices = value
	}
	if value, ok := _c.mutation.ExternalID(); ok {
		_spec.SetField(translation.FieldExternalID, field.TypeString, value)
		_node.ExternalID = value
	}
	if value, ok := _c.mutation.LanguagePair(); ok {
		_spec.SetField(translation.FieldLanguagePair, field.TypeString, value)
		_node.LanguagePair = value
	}
	if value, ok := _c.mutation.OwnerID(); ok {
		_spec.SetField(translation.FieldOwnerID, field.TypeString, value)
		_node.OwnerID = value
	}
	if nodes := _c.mutation.TranscriptionStatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   translation.TranscriptionStatsTable,
			Columns: []string{translation.TranscriptionStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transcriptionstats.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TranslationCreateBulk is the builder for creating many Translation entities in bulk.
type TranslationCreateBulk struct {
	config
	err      error
	builders []*TranslationCreate
}

// Save creates the Translation entities in the database.
func (_c *TranslationCreateBulk) Save(ctx context.Context) ([]*Translation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Translation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TranslationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TranslationCreateBulk) SaveX(ctx context.Context) []*Translation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TranslationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TranslationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
