// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"ent/ent/predicate"
	"ent/ent/transcriptionstats"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TranscriptionStatsDelete is the builder for deleting a TranscriptionStats entity.
type TranscriptionStatsDelete struct {
	config
	hooks    []Hook
	mutation *TranscriptionStatsMutation
}

// Where appends a list predicates to the TranscriptionStatsDelete builder.
func (_d *TranscriptionStatsDelete) Where(ps ...predicate.TranscriptionStats) *TranscriptionStatsDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TranscriptionStatsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TranscriptionStatsDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TranscriptionStatsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(transcriptionstats.Table, sqlgraph.NewFieldSpec(transcriptionstats.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TranscriptionStatsDeleteOne is the builder for deleting a single TranscriptionStats entity.
type TranscriptionStatsDeleteOne struct {
	_d *TranscriptionStatsDelete
}

// Where appends a list predicates to the TranscriptionStatsDelete builder.
func (_d *TranscriptionStatsDeleteOne) Where(ps ...predicate.TranscriptionStats) *TranscriptionStatsDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TranscriptionStatsDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{transcriptionstats.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TranscriptionStatsDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
