// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"ent/ent/predicate"
	"ent/ent/transcriptionstats"
	"ent/ent/translation"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TranslationQuery is the builder for querying Translation entities.
type TranslationQuery struct {
	config
	ctx                    *QueryContext
	order                  []translation.OrderOption
	inters                 []Interceptor
	predicates             []predicate.Translation
	withTranscriptionStats *TranscriptionStatsQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TranslationQuery builder.
func (_q *TranslationQuery) Where(ps ...predicate.Translation) *TranslationQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *TranslationQuery) Limit(limit int) *TranslationQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *TranslationQuery) Offset(offset int) *TranslationQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *TranslationQuery) Unique(unique bool) *TranslationQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *TranslationQuery) Order(o ...translation.OrderOption) *TranslationQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryTranscriptionStats chains the current query on the "transcription_stats" edge.
func (_q *TranslationQuery) QueryTranscriptionStats() *TranscriptionStatsQuery {
	query := (&TranscriptionStatsClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(translation.Table, translation.FieldID, selector),
			sqlgraph.To(transcriptionstats.Table, transcriptionstats.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, translation.TranscriptionStatsTable, translation.TranscriptionStatsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Translation entity from the query.
// Returns a *NotFoundError when no Translation was found.
func (_q *TranslationQuery) First(ctx context.Context) (*Translation, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{translation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *TranslationQuery) FirstX(ctx context.Context) *Translation {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Translation ID from the query.
// Returns a *NotFoundError when no Translation ID was found.
func (_q *TranslationQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{translation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *TranslationQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Translation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Translation entity is found.
// Returns a *NotFoundError when no Translation entities are found.
func (_q *TranslationQuery) Only(ctx context.Context) (*Translation, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{translation.Label}
	default:
		return nil, &NotSingularError{translation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *TranslationQuery) OnlyX(ctx context.Context) *Translation {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Translation ID in the query.
// Returns a *NotSingularError when more than one Translation ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *TranslationQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{translation.Label}
	default:
		err = &NotSingularError{translation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *TranslationQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Translations.
func (_q *TranslationQuery) All(ctx context.Context) ([]*Translation, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Translation, *TranslationQuery]()
	return withInterceptors[[]*Translation](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *TranslationQuery) AllX(ctx context.Context) []*Translation {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Translation IDs.
func (_q *TranslationQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(translation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *TranslationQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *TranslationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*TranslationQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *TranslationQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *TranslationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *TranslationQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TranslationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *TranslationQuery) Clone() *TranslationQuery {
	if _q == nil {
		return nil
	}
	return &TranslationQuery{
		config:                 _q.config,
		ctx:                    _q.ctx.Clone(),
		order:                  append([]translation.OrderOption{}, _q.order...),
		inters:                 append([]Interceptor{}, _q.inters...),
		predicates:             append([]predicate.Translation{}, _q.predicates...),
		withTranscriptionStats: _q.withTranscriptionStats.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithTranscriptionStats tells the query-builder to eager-load the nodes that are connected to
// the "transcription_stats" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TranslationQuery) WithTranscriptionStats(opts ...func(*TranscriptionStatsQuery)) *TranslationQuery {
	query := (&TranscriptionStatsClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTranscriptionStats = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Content string `json:"content,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Translation.Query().
//		GroupBy(translation.FieldContent).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *TranslationQuery) GroupBy(field string, fields ...string) *TranslationGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TranslationGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = translation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Content string `json:"content,omitempty"`
//	}
//
//	client.Translation.Query().
//		Select(translation.FieldContent).
//		Scan(ctx, &v)
func (_q *TranslationQuery) Select(fields ...string) *TranslationSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &TranslationSelect{TranslationQuery: _q}
	sbuild.label = translation.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TranslationSelect configured with the given aggregations.
func (_q *TranslationQuery) Aggregate(fns ...AggregateFunc) *TranslationSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *TranslationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !translation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *TranslationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Translation, error) {
	var (
		nodes       = []*Translation{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withTranscriptionStats != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Translation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Translation{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withTranscriptionStats; query != nil {
		if err := _q.loadTranscriptionStats(ctx, query, nodes,
			func(n *Translation) { n.Edges.TranscriptionStats = []*TranscriptionStats{} },
			func(n *Translation, e *TranscriptionStats) {
				n.Edges.TranscriptionStats = append(n.Edges.TranscriptionStats, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *TranslationQuery) loadTranscriptionStats(ctx context.Context, query *TranscriptionStatsQuery, nodes []*Translation, init func(*Translation), assign func(*Translation, *TranscriptionStats)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Translation)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(transcriptionstats.FieldTranslationID)
	}
	query.Where(predicate.TranscriptionStats(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(translation.TranscriptionStatsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TranslationID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "translation_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *TranslationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *TranslationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(translation.Table, translation.Columns, sqlgraph.NewFieldSpec(translation.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, translation.FieldID)
		for i := range fields {
			if fields[i] != translation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *TranslationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(translation.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = translation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TranslationGroupBy is the group-by builder for Translation entities.
type TranslationGroupBy struct {
	selector
	build *TranslationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *TranslationGroupBy) Aggregate(fns ...AggregateFunc) *TranslationGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *TranslationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TranslationQuery, *TranslationGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *TranslationGroupBy) sqlScan(ctx context.Context, root *TranslationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TranslationSelect is the builder for selecting fields of Translation entities.
type TranslationSelect struct {
	*TranslationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *TranslationSelect) Aggregate(fns ...AggregateFunc) *TranslationSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *TranslationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TranslationQuery, *TranslationSelect](ctx, _s.TranslationQuery, _s, _s.inters, v)
}

func (_s *TranslationSelect) sqlScan(ctx context.Context, root *TranslationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
