// Code generated by ent, DO NOT EDIT.

package transcriptionstats

import (
	"ent/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldLTE(FieldID, id))
}

// Duration applies equality check predicate on the "duration" field. It's identical to DurationEQ.
func Duration(v int64) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldEQ(FieldDuration, v))
}

// InputToken applies equality check predicate on the "input_token" field. It's identical to InputTokenEQ.
func InputToken(v int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldEQ(FieldInputToken, v))
}

// OutputToken applies equality check predicate on the "output_token" field. It's identical to OutputTokenEQ.
func OutputToken(v int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldEQ(FieldOutputToken, v))
}

// ModelName applies equality check predicate on the "model_name" field. It's identical to ModelNameEQ.
func ModelName(v string) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldEQ(FieldModelName, v))
}

// Cost applies equality check predicate on the "cost" field. It's identical to CostEQ.
func Cost(v float64) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldEQ(FieldCost, v))
}

// OwnerID applies equality check predicate on the "owner_id" field. It's identical to OwnerIDEQ.
func OwnerID(v string) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldEQ(FieldOwnerID, v))
}

// TranslationID applies equality check predicate on the "translation_id" field. It's identical to TranslationIDEQ.
func TranslationID(v int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldEQ(FieldTranslationID, v))
}

// DurationEQ applies the EQ predicate on the "duration" field.
func DurationEQ(v int64) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldEQ(FieldDuration, v))
}

// DurationNEQ applies the NEQ predicate on the "duration" field.
func DurationNEQ(v int64) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldNEQ(FieldDuration, v))
}

// DurationIn applies the In predicate on the "duration" field.
func DurationIn(vs ...int64) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldIn(FieldDuration, vs...))
}

// DurationNotIn applies the NotIn predicate on the "duration" field.
func DurationNotIn(vs ...int64) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldNotIn(FieldDuration, vs...))
}

// DurationGT applies the GT predicate on the "duration" field.
func DurationGT(v int64) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldGT(FieldDuration, v))
}

// DurationGTE applies the GTE predicate on the "duration" field.
func DurationGTE(v int64) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldGTE(FieldDuration, v))
}

// DurationLT applies the LT predicate on the "duration" field.
func DurationLT(v int64) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldLT(FieldDuration, v))
}

// DurationLTE applies the LTE predicate on the "duration" field.
func DurationLTE(v int64) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldLTE(FieldDuration, v))
}

// InputTokenEQ applies the EQ predicate on the "input_token" field.
func InputTokenEQ(v int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldEQ(FieldInputToken, v))
}

// InputTokenNEQ applies the NEQ predicate on the "input_token" field.
func InputTokenNEQ(v int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldNEQ(FieldInputToken, v))
}

// InputTokenIn applies the In predicate on the "input_token" field.
func InputTokenIn(vs ...int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldIn(FieldInputToken, vs...))
}

// InputTokenNotIn applies the NotIn predicate on the "input_token" field.
func InputTokenNotIn(vs ...int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldNotIn(FieldInputToken, vs...))
}

// InputTokenGT applies the GT predicate on the "input_token" field.
func InputTokenGT(v int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldGT(FieldInputToken, v))
}

// InputTokenGTE applies the GTE predicate on the "input_token" field.
func InputTokenGTE(v int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldGTE(FieldInputToken, v))
}

// InputTokenLT applies the LT predicate on the "input_token" field.
func InputTokenLT(v int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldLT(FieldInputToken, v))
}

// InputTokenLTE applies the LTE predicate on the "input_token" field.
func InputTokenLTE(v int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldLTE(FieldInputToken, v))
}

// OutputTokenEQ applies the EQ predicate on the "output_token" field.
func OutputTokenEQ(v int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldEQ(FieldOutputToken, v))
}

// OutputTokenNEQ applies the NEQ predicate on the "output_token" field.
func OutputTokenNEQ(v int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldNEQ(FieldOutputToken, v))
}

// OutputTokenIn applies the In predicate on the "output_token" field.
func OutputTokenIn(vs ...int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldIn(FieldOutputToken, vs...))
}

// OutputTokenNotIn applies the NotIn predicate on the "output_token" field.
func OutputTokenNotIn(vs ...int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldNotIn(FieldOutputToken, vs...))
}

// OutputTokenGT applies the GT predicate on the "output_token" field.
func OutputTokenGT(v int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldGT(FieldOutputToken, v))
}

// OutputTokenGTE applies the GTE predicate on the "output_token" field.
func OutputTokenGTE(v int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldGTE(FieldOutputToken, v))
}

// OutputTokenLT applies the LT predicate on the "output_token" field.
func OutputTokenLT(v int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldLT(FieldOutputToken, v))
}

// OutputTokenLTE applies the LTE predicate on the "output_token" field.
func OutputTokenLTE(v int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldLTE(FieldOutputToken, v))
}

// ModelNameEQ applies the EQ predicate on the "model_name" field.
func ModelNameEQ(v string) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldEQ(FieldModelName, v))
}

// ModelNameNEQ applies the NEQ predicate on the "model_name" field.
func ModelNameNEQ(v string) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldNEQ(FieldModelName, v))
}

// ModelNameIn applies the In predicate on the "model_name" field.
func ModelNameIn(vs ...string) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldIn(FieldModelName, vs...))
}

// ModelNameNotIn applies the NotIn predicate on the "model_name" field.
func ModelNameNotIn(vs ...string) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldNotIn(FieldModelName, vs...))
}

// ModelNameGT applies the GT predicate on the "model_name" field.
func ModelNameGT(v string) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldGT(FieldModelName, v))
}

// ModelNameGTE applies the GTE predicate on the "model_name" field.
func ModelNameGTE(v string) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldGTE(FieldModelName, v))
}

// ModelNameLT applies the LT predicate on the "model_name" field.
func ModelNameLT(v string) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldLT(FieldModelName, v))
}

// ModelNameLTE applies the LTE predicate on the "model_name" field.
func ModelNameLTE(v string) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldLTE(FieldModelName, v))
}

// ModelNameContains applies the Contains predicate on the "model_name" field.
func ModelNameContains(v string) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldContains(FieldModelName, v))
}

// ModelNameHasPrefix applies the HasPrefix predicate on the "model_name" field.
func ModelNameHasPrefix(v string) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldHasPrefix(FieldModelName, v))
}

// ModelNameHasSuffix applies the HasSuffix predicate on the "model_name" field.
func ModelNameHasSuffix(v string) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldHasSuffix(FieldModelName, v))
}

// ModelNameEqualFold applies the EqualFold predicate on the "model_name" field.
func ModelNameEqualFold(v string) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldEqualFold(FieldModelName, v))
}

// ModelNameContainsFold applies the ContainsFold predicate on the "model_name" field.
func ModelNameContainsFold(v string) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldContainsFold(FieldModelName, v))
}

// CostEQ applies the EQ predicate on the "cost" field.
func CostEQ(v float64) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldEQ(FieldCost, v))
}

// CostNEQ applies the NEQ predicate on the "cost" field.
func CostNEQ(v float64) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldNEQ(FieldCost, v))
}

// CostIn applies the In predicate on the "cost" field.
func CostIn(vs ...float64) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldIn(FieldCost, vs...))
}

// CostNotIn applies the NotIn predicate on the "cost" field.
func CostNotIn(vs ...float64) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldNotIn(FieldCost, vs...))
}

// CostGT applies the GT predicate on the "cost" field.
func CostGT(v float64) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldGT(FieldCost, v))
}

// CostGTE applies the GTE predicate on the "cost" field.
func CostGTE(v float64) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldGTE(FieldCost, v))
}

// CostLT applies the LT predicate on the "cost" field.
func CostLT(v float64) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldLT(FieldCost, v))
}

// CostLTE applies the LTE predicate on the "cost" field.
func CostLTE(v float64) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldLTE(FieldCost, v))
}

// OwnerIDEQ applies the EQ predicate on the "owner_id" field.
func OwnerIDEQ(v string) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldEQ(FieldOwnerID, v))
}

// OwnerIDNEQ applies the NEQ predicate on the "owner_id" field.
func OwnerIDNEQ(v string) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldNEQ(FieldOwnerID, v))
}

// OwnerIDIn applies the In predicate on the "owner_id" field.
func OwnerIDIn(vs ...string) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldIn(FieldOwnerID, vs...))
}

// OwnerIDNotIn applies the NotIn predicate on the "owner_id" field.
func OwnerIDNotIn(vs ...string) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldNotIn(FieldOwnerID, vs...))
}

// OwnerIDGT applies the GT predicate on the "owner_id" field.
func OwnerIDGT(v string) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldGT(FieldOwnerID, v))
}

// OwnerIDGTE applies the GTE predicate on the "owner_id" field.
func OwnerIDGTE(v string) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldGTE(FieldOwnerID, v))
}

// OwnerIDLT applies the LT predicate on the "owner_id" field.
func OwnerIDLT(v string) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldLT(FieldOwnerID, v))
}

// OwnerIDLTE applies the LTE predicate on the "owner_id" field.
func OwnerIDLTE(v string) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldLTE(FieldOwnerID, v))
}

// OwnerIDContains applies the Contains predicate on the "owner_id" field.
func OwnerIDContains(v string) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldContains(FieldOwnerID, v))
}

// OwnerIDHasPrefix applies the HasPrefix predicate on the "owner_id" field.
func OwnerIDHasPrefix(v string) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldHasPrefix(FieldOwnerID, v))
}

// OwnerIDHasSuffix applies the HasSuffix predicate on the "owner_id" field.
func OwnerIDHasSuffix(v string) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldHasSuffix(FieldOwnerID, v))
}

// OwnerIDEqualFold applies the EqualFold predicate on the "owner_id" field.
func OwnerIDEqualFold(v string) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldEqualFold(FieldOwnerID, v))
}

// OwnerIDContainsFold applies the ContainsFold predicate on the "owner_id" field.
func OwnerIDContainsFold(v string) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldContainsFold(FieldOwnerID, v))
}

// TranslationIDEQ applies the EQ predicate on the "translation_id" field.
func TranslationIDEQ(v int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldEQ(FieldTranslationID, v))
}

// TranslationIDNEQ applies the NEQ predicate on the "translation_id" field.
func TranslationIDNEQ(v int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldNEQ(FieldTranslationID, v))
}

// TranslationIDIn applies the In predicate on the "translation_id" field.
func TranslationIDIn(vs ...int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldIn(FieldTranslationID, vs...))
}

// TranslationIDNotIn applies the NotIn predicate on the "translation_id" field.
func TranslationIDNotIn(vs ...int) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.FieldNotIn(FieldTranslationID, vs...))
}

// HasTranslation applies the HasEdge predicate on the "translation" edge.
func HasTranslation() predicate.TranscriptionStats {
	return predicate.TranscriptionStats(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TranslationTable, TranslationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTranslationWith applies the HasEdge predicate on the "translation" edge with a given conditions (other predicates).
func HasTranslationWith(preds ...predicate.Translation) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(func(s *sql.Selector) {
		step := newTranslationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TranscriptionStats) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TranscriptionStats) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TranscriptionStats) predicate.TranscriptionStats {
	return predicate.TranscriptionStats(sql.NotPredicates(p))
}
