// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// LanguageDetection is the predicate function for languagedetection builders.
type LanguageDetection func(*sql.Selector)

// TranscriptionStats is the predicate function for transcriptionstats builders.
type TranscriptionStats func(*sql.Selector)

// Translation is the predicate function for translation builders.
type Translation func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
